#!/bin/tcsh -f

# CMSC 216, Spring 2021, Project #11
# Public test 6 (public6)
#
# Tests the program with two filenames on the command line, so two threads
# will be created.  The files are larger than those in the previous test.
#
# (c) Larry Herman, 2021.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./longlines2-threaded.x public6.cprogram1 public6.cprogram2
