#!/bin/tcsh -f

# CMSC 216, Spring 2021, Project #11
# Public test 5 (public5)
#
# Tests the program with two filenames on the command line, so two threads will
# be created.
#
# (c) Larry Herman, 2021.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./longlines2-threaded.x public5.cprogram1 public5.cprogram2
