#!/bin/tcsh -f

# CMSC 216, Spring 2021, Project #11
# Public test 8 (public8)
#
# Tests the program with two filenames on the command line, so two threads
# will be created.  The files are the same as those in the fifth public
# test, so the results should be the same.  The only difference is that this
# test uses valgrind to check for memory leaks and corruption of the heap.
#
# (c) Larry Herman, 2021.  You are allowed to use this
# code yourself, but not to provide it to anyone else.

valgrind -q --leak-check=full --error-exitcode=100 \
  ./longlines2-threaded.x public5.cprogram1 public5.cprogram2

if ($status == 0) then
  # normal exit
  echo "Success!  longlines2-threaded.x didn't have any memory problems."
  exit 0
else
  # error exit
  echo "Problem!  longlines2-threaded.x had memory leaks or other memory problems."
  exit 1
endif

