#!/bin/tcsh -f

# CMSC 216, Spring 2021, Project #11
# Public test 4 (public4)
#
# Tests the program with just one filename on the command line, meaning only
# one thread will be created (besides the main thread).  The file exists but
# is an empty file, so it should have zero lines, works and characters.
#
# (c) Larry Herman, 2021.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./longlines2-threaded.x public4.cprogram
